# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Create the file
          command: "python main.py"
      - store_artifacts:
          name: Keep the file
          path: "snippets/Emoji Pack Update.alfredsnippets"
  tests:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Run some tests
          command: echo 'Nothing yet'


workflows:
  version: 2
  build:
    jobs:
      - build
      - tests